# Generated by Django 4.0.3 on 2022-03-23 19:20

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('chart_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('chart_type', wagtail.blocks.ChoiceBlock(choices=[('bar', 'Line/Bar/Area chart'), ('pie', 'Pie chart'), ('doughnut', 'Doughnut chart'), ('radar', 'Radar chart'), ('polar', 'Polar chart')])), ('datasets', wagtail.blocks.TextBlock(default='[]'))]))], blank=True, verbose_name='Page body'),
        ),
    ]
